### ISSUE TITLE
"Grant has been used before"-feil

### ISSUE THREAD

**Issue by SveinungFjaer** [ks-no/fiks-maskinporten#112]
Opplever oftere 500-feil med feilmeldingen
`java.lang.RuntimeException: Http response code: 400, url: 'https://maskinporten.no/token', scopes: '[ks:fiks]', message: '{"error":"invalid_grant","error_description":"Invalid assertion. Grant has been used before. (correlation id: e59389be-1468-52b8-85cb-34cf9fe4971e)"}`

**Comment by zapodot** [comment]
Ser ut til å være en retry som kan forårsake dette. Prøver å bruke en annen klient mot Maskinporten der vi kan ha mer kontroll på dette
