### ISSUE TITLE
Gjenbruk av httpClient og mulighet for å konfigurere den

### ISSUE THREAD

**Issue by simenstoa** [ks-no/fiks-maskinporten#235]
Hei!

Og takk for at dere har laget et open-source bibliotek for dette. Vi har lyst til ta det i bruk, men skulle gjerne hatt mulighet til å konfigurere opp timeouts osv for http-klienten. Det hadde også vært en fordel om `ClosableHttpClient` bare ble instansiert en gang, så vi kan gjenbruke connection pools osv.

Kan lage en PR på det hvis det er ønskelig, men ser ikke ut som jeg har tilgang til å pushe opp noen brancher til repoet.

Mvh Simen Støa

**Comment by zapodot** [comment]
Hei Simen! For å lage en PR kan du forke vårt repository til din egen konto og lage PR mot oss igjen. Da vil vi se på den så fort som mulig.

**Comment by simenstoa** [comment]
Takk for svar! Vi endte opp med å ikke bruke et bibliotek for dette likevel, så jeg lukker bare issuet. 😊

**Comment by zapodot** [comment]
Greit det @simenstoa! Vi har implementert denne funksjonen i vår siste versjon 2.0.0. Dersom du trenger den en annen gang ser du hvordan du konfigurerer det her: https://github.com/ks-no/fiks-maskinporten#bruk-egen-closeablehttpclient
